# list of samples with name and relative path without "_R*.fastq.gz"
samples: [
  "K27me3_2-2-1_liver",
  "K27me3_2-2-2_liver",
  "K27me3_2-2-3_liver",
  "K27me3_9-2-1_liver",
  "K27me3_9-2-2_liver",
  "K27me3_9-2-3_liver",
  "K27me3_2-6-1_liver",
  "K27me3_2-6-2_liver",
  "K27me3_9-6-1_liver",
  "K27me3_9-6-2_liver",
  "K27me3_2-12-1_liver",
  "K27me3_2-12-2_liver",
  "K27me3_2-12-3_liver",
  "K27me3_9-12-1_liver",
  "K27me3_9-12-2_liver",
  "K27me3_9-12-3_liver",
  ]

# maximum number of threads to be applied to the pipeline
threads: 10

genomes:
  cmv_mouse: "~/sds-hd/sd21j005/conradin/projects/seq_runs/episome_bisulfite_001/genomes/pPl04/pPl04_mouse.bowtie2"
  cmv: "~/sds-hd/sd21j005/conradin/projects/seq_runs/episome_bisulfite_001/genomes/pPl04/pPl04.bowtie2"
